import argparse
from copy import deepcopy
from typing import Any, Dict, List

from database import add_book, initialize_database, get_connection


DUMMY_BOOKS: List[Dict[str, Any]] = [
    {
        "title": "Pythonで学ぶ機械学習",
        "authors": "山田 太郎",
        "categories": "技術,Python,機械学習",
        "description": "Pythonを使い、分類や回帰など機械学習の基礎を実践的に学べる入門書です。",
        "publisher": "技術書出版",
        "published_date": "2023-01-15",
        "isbn": "9780000000001",
        "page_count": 320,
        "thumbnail_url": "",
        "status": "読了",
        "rating": 5,
        "started_at": "2024-01-10",
        "completed_at": "2024-01-28",
        "memo": "サンプルコードが分かりやすかった",
    },
    {
        "title": "データ分析のための統計入門",
        "authors": "高橋 美咲",
        "categories": "技術,統計,データ分析",
        "description": "平均や分散から回帰分析まで、データ分析に必要な統計学を解説します。",
        "publisher": "数理書房",
        "published_date": "2022-06-20",
        "isbn": "9780000000002",
        "page_count": 286,
        "thumbnail_url": "",
        "status": "読了",
        "rating": 4,
        "started_at": "2024-02-05",
        "completed_at": "2024-02-25",
        "memo": "回帰分析の章を復習したい",
    },
    {
        "title": "はじめてのWebアプリ開発",
        "authors": "中村 健",
        "categories": "技術,Web,プログラミング",
        "description": "HTML、CSS、Pythonを使ってWebアプリを作る方法を学べます。",
        "publisher": "コード出版",
        "published_date": "2024-03-01",
        "isbn": "9780000000003",
        "page_count": 410,
        "thumbnail_url": "",
        "status": "読書中",
        "rating": 4,
        "started_at": "2024-04-12",
        "completed_at": None,
        "memo": "Streamlitの部分まで読んだ",
    },
    {
        "title": "人工知能は物語を作れるか",
        "authors": "木村 拓海",
        "categories": "科学,人工知能,社会",
        "description": "生成AIと創作活動の関係を、技術と文化の両面から考察します。",
        "publisher": "未来評論社",
        "published_date": "2023-09-10",
        "isbn": "9780000000004",
        "page_count": 248,
        "thumbnail_url": "",
        "status": "読書中",
        "rating": 3,
        "started_at": "2024-05-01",
        "completed_at": None,
        "memo": "AIと著作権の章が興味深い",
    },
    {
        "title": "夜に読む短編小説",
        "authors": "鈴木 一郎",
        "categories": "小説,文学,短編集",
        "description": "日常の小さな出来事を描いた、静かな雰囲気の短編小説集です。",
        "publisher": "文芸社",
        "published_date": "2021-05-01",
        "isbn": "9780000000005",
        "page_count": 140,
        "thumbnail_url": "",
        "status": "読書中",
        "rating": 5,
        "started_at": "2024-05-18",
        "completed_at": None,
        "memo": "寝る前に少しずつ読む",
    },
    {
        "title": "海辺の喫茶店",
        "authors": "小林 葵",
        "categories": "小説,日常,ヒューマンドラマ",
        "description": "海辺の喫茶店を訪れる人々の人生を描いた連作小説です。",
        "publisher": "青空文庫出版",
        "published_date": "2020-07-18",
        "isbn": "9780000000006",
        "page_count": 224,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "表紙に惹かれて購入",
    },
    {
        "title": "消えた時計塔の謎",
        "authors": "伊藤 蓮",
        "categories": "小説,ミステリー,推理",
        "description": "古い時計塔で起きた失踪事件を大学生探偵が追うミステリーです。",
        "publisher": "探究社",
        "published_date": "2019-11-02",
        "isbn": "9780000000007",
        "page_count": 368,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "長期休暇に読む予定",
    },
    {
        "title": "世界の美術館を歩く",
        "authors": "藤田 玲奈",
        "categories": "芸術,美術,旅行",
        "description": "世界各地の美術館と代表的な収蔵作品を写真とともに紹介します。",
        "publisher": "文化紀行社",
        "published_date": "2022-10-15",
        "isbn": "9780000000009",
        "page_count": 196,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "旅行先を考えるときに読みたい",
    },
    {
        "title": "デザインの基本ルール",
        "authors": "松本 彩",
        "categories": "芸術,デザイン,実用",
        "description": "配色、余白、文字組みなど、見やすいデザインの基本を解説します。",
        "publisher": "クリエイティブ社",
        "published_date": "2021-04-08",
        "isbn": "9780000000010",
        "page_count": 212,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "プレゼン資料作成に役立てたい",
    },
    {
        "title": "今日から始める読書習慣",
        "authors": "佐藤 花子",
        "categories": "自己啓発,読書,習慣",
        "description": "忙しい生活の中で読書時間を確保し、習慣化する方法を提案します。",
        "publisher": "学び舎",
        "published_date": "2022-08-01",
        "isbn": "9780000000011",
        "page_count": 180,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "積読対策の参考にする",
    },
    {
        "title": "先延ばしをやめる小さな方法",
        "authors": "吉田 直樹",
        "categories": "自己啓発,心理,習慣",
        "description": "行動を始められない原因を整理し、小さく着手する方法を紹介します。",
        "publisher": "生活改善出版",
        "published_date": "2020-02-14",
        "isbn": "9780000000012",
        "page_count": 156,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "課題の先延ばし対策",
    },
    {
        "title": "大学生のためのプレゼン術",
        "authors": "森田 和也",
        "categories": "実用,プレゼンテーション,学習",
        "description": "発表の構成、スライド作成、話し方を具体例とともに説明します。",
        "publisher": "キャンパス出版",
        "published_date": "2023-04-05",
        "isbn": "9780000000013",
        "page_count": 198,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "授業発表の前に読む",
    },
    {
        "title": "一人暮らしの簡単レシピ",
        "authors": "井上 真琴",
        "categories": "料理,生活,実用",
        "description": "少ない材料と調理器具で作れる手軽な料理を紹介します。",
        "publisher": "食卓社",
        "published_date": "2018-09-12",
        "isbn": "9780000000014",
        "page_count": 128,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "簡単な夕食を増やしたい",
    },
    {
        "title": "眠れない夜の宇宙図鑑",
        "authors": "石川 宙",
        "categories": "科学,宇宙,図鑑",
        "description": "星や惑星、銀河の仕組みを美しい写真とやさしい文章で紹介します。",
        "publisher": "星空書房",
        "published_date": "2021-12-20",
        "isbn": "9780000000015",
        "page_count": 272,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "写真を眺めるために購入",
    },
        {
        "title": "やさしいネットワーク入門",
        "authors": "加藤 翔太",
        "categories": "技術,ネットワーク,IT",
        "description": "インターネット通信の仕組みやTCP/IP、セキュリティの基礎を図解で学べます。",
        "publisher": "情報技術社",
        "published_date": "2022-02-18",
        "isbn": "9780000000016",
        "page_count": 264,
        "thumbnail_url": "",
        "status": "読了",
        "rating": 3,
        "started_at": "2024-03-02",
        "completed_at": "2024-03-19",
        "memo": "授業内容の復習に使った",
    },
    {
        "title": "アルゴリズム図鑑",
        "authors": "田中 遼",
        "categories": "技術,アルゴリズム,プログラミング",
        "description": "探索、ソート、グラフなど代表的なアルゴリズムをイラストで解説します。",
        "publisher": "コードラボ出版",
        "published_date": "2023-07-12",
        "isbn": "9780000000017",
        "page_count": 336,
        "thumbnail_url": "",
        "status": "読了",
        "rating": 5,
        "started_at": "2024-04-01",
        "completed_at": "2024-04-25",
        "memo": "図が多く理解しやすかった",
    },
    {
        "title": "ゼロからわかるデータベース",
        "authors": "斎藤 奈々",
        "categories": "技術,データベース,SQL",
        "description": "データベース設計、SQL、正規化の基礎を演習形式で学べる本です。",
        "publisher": "データ出版",
        "published_date": "2021-10-05",
        "isbn": "9780000000018",
        "page_count": 298,
        "thumbnail_url": "",
        "status": "読書中",
        "rating": 4,
        "started_at": "2024-06-03",
        "completed_at": None,
        "memo": "SQLiteの章を読んでいる",
    },
    {
        "title": "暗号技術のしくみ",
        "authors": "宮本 剛",
        "categories": "技術,暗号,セキュリティ",
        "description": "共通鍵暗号、公開鍵暗号、ハッシュ関数の仕組みを数学とともに解説します。",
        "publisher": "理工学出版",
        "published_date": "2020-06-25",
        "isbn": "9780000000019",
        "page_count": 384,
        "thumbnail_url": "",
        "status": "読書中",
        "rating": 3,
        "started_at": "2024-06-15",
        "completed_at": None,
        "memo": "数式の部分をゆっくり読みたい",
    },
    {
        "title": "VRが変えるコミュニケーション",
        "authors": "橋本 未来",
        "categories": "技術,VR,コミュニケーション",
        "description": "仮想空間での身体表現や対人関係が人の心理に与える影響を紹介します。",
        "publisher": "デジタル未来社",
        "published_date": "2024-02-22",
        "isbn": "9780000000020",
        "page_count": 232,
        "thumbnail_url": "",
        "status": "読書中",
        "rating": 5,
        "started_at": "2024-07-01",
        "completed_at": None,
        "memo": "研究テーマの参考にしたい",
    },
    {
        "title": "雪国の郵便配達人",
        "authors": "青木 千尋",
        "categories": "小説,文学,ヒューマンドラマ",
        "description": "雪深い町で手紙を届ける郵便配達人と住民たちの交流を描く物語です。",
        "publisher": "白樺書房",
        "published_date": "2018-01-19",
        "isbn": "9780000000021",
        "page_count": 310,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "冬に読みたい",
    },
    {
        "title": "透明な記憶",
        "authors": "渡辺 沙季",
        "categories": "小説,SF,ミステリー",
        "description": "他人の記憶を映像として見る技術が普及した社会で起きる事件を描きます。",
        "publisher": "新星文庫",
        "published_date": "2023-11-08",
        "isbn": "9780000000022",
        "page_count": 416,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "設定が面白そう",
    },
    {
        "title": "京都あやかし古書店",
        "authors": "山口 朱音",
        "categories": "小説,ファンタジー,和風",
        "description": "京都の古書店を舞台に、本に宿るあやかしと店員の交流を描きます。",
        "publisher": "月夜出版",
        "published_date": "2022-09-17",
        "isbn": "9780000000023",
        "page_count": 278,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "和風ファンタジーに興味がある",
    },
    {
        "title": "深海都市の子どもたち",
        "authors": "大野 海斗",
        "categories": "小説,SF,冒険",
        "description": "海面上昇後の未来で、深海都市に暮らす子どもたちが地上を目指す冒険小説です。",
        "publisher": "オーシャン文庫",
        "published_date": "2021-03-30",
        "isbn": "9780000000024",
        "page_count": 352,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "世界観に惹かれて購入",
    },
    {
        "title": "名画の見方が変わる本",
        "authors": "西村 絵里",
        "categories": "芸術,美術史,教養",
        "description": "西洋絵画の構図、色彩、象徴表現を初心者向けに解説します。",
        "publisher": "アート教養社",
        "published_date": "2020-08-28",
        "isbn": "9780000000025",
        "page_count": 240,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "美術館に行く前に読みたい",
    },
    {
        "title": "色彩と心理のデザイン",
        "authors": "清水 香織",
        "categories": "芸術,デザイン,心理",
        "description": "色が人の感情や行動に与える影響と、デザインへの活用方法を紹介します。",
        "publisher": "クリエイト書房",
        "published_date": "2023-05-16",
        "isbn": "9780000000026",
        "page_count": 208,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "Webデザインの配色に活かしたい",
    },
    {
        "title": "大学生活を整える時間管理術",
        "authors": "遠藤 真由",
        "categories": "自己啓発,時間管理,大学生活",
        "description": "授業、課題、アルバイトを両立するための時間管理方法を解説します。",
        "publisher": "キャンパスライフ社",
        "published_date": "2022-03-25",
        "isbn": "9780000000027",
        "page_count": 172,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "課題管理を改善したい",
    },
    {
        "title": "伝わる文章の書き方",
        "authors": "福田 誠",
        "categories": "実用,文章術,コミュニケーション",
        "description": "レポートやメールを分かりやすく書くための構成と表現を解説します。",
        "publisher": "ことば出版",
        "published_date": "2019-04-11",
        "isbn": "9780000000028",
        "page_count": 190,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "レポート作成に役立てたい",
    },
    {
        "title": "行動経済学で読み解く選択",
        "authors": "松田 慎一",
        "categories": "社会科学,経済,心理",
        "description": "人が合理的ではない選択をする理由を、身近な事例から説明します。",
        "publisher": "知識の森出版",
        "published_date": "2021-07-07",
        "isbn": "9780000000029",
        "page_count": 304,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "推薦システムとの関係も考えたい",
    },
    {
        "title": "身近な気象の科学",
        "authors": "小川 晴彦",
        "categories": "科学,気象,自然",
        "description": "雲、雨、台風、天気予報の仕組みを身近な現象から解説します。",
        "publisher": "自然科学社",
        "published_date": "2020-12-03",
        "isbn": "9780000000030",
        "page_count": 256,
        "thumbnail_url": "",
        "status": "未読",
        "rating": 0,
        "started_at": None,
        "completed_at": None,
        "memo": "天気アプリを見るときの参考にしたい",
    },
]


def _clear_existing_books(db_path: str) -> None:
    """Remove previously seeded books before inserting a fresh set."""
    with get_connection(db_path) as conn:
        conn.execute("DELETE FROM books")
        conn.commit()


def seed_dummy_books(db_path: str = "books.db", count: int = 15, reset: bool = True) -> int:
    """ローカルテスト用のダミー書籍を登録する。"""
    initialize_database(db_path)

    if reset:
        _clear_existing_books(db_path)

    if count <= 0:
        return 0

    inserted = 0

    for index in range(count):
        # countが15を超えた場合も、データを循環して使用する
        template = DUMMY_BOOKS[index % len(DUMMY_BOOKS)]
        book = deepcopy(template)

        # 15冊を超えて追加するときは重複を避ける
        cycle = index // len(DUMMY_BOOKS)
        if cycle > 0:
            book["title"] = f"{book['title']} テスト版{cycle + 1}"
            book["isbn"] = f"978{index + 1:010d}"

        add_book(book, db_path=db_path)
        inserted += 1

    return inserted


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Insert dummy books for testing"
    )
    parser.add_argument(
        "--db-path",
        default="books.db",
        help="SQLite database path",
    )
    parser.add_argument(
        "--count",
        type=int,
        default=15,
        help="Number of dummy books to create",
    )
    parser.add_argument(
        "--no-reset",
        action="store_true",
        help="Keep existing books and append instead of replacing them",
    )
    args = parser.parse_args()

    inserted = seed_dummy_books(
        db_path=args.db_path,
        count=args.count,
        reset=not args.no_reset,
    )
    print(f"Inserted {inserted} dummy books into {args.db_path}")